### ISSUE TITLE
Using Impeller as a rendering backend

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/embedder#15]

**Comment by swift-kim** [comment]
Vulkan for Impeller has been disabled on engine build: https://github.com/flutter-tizen/engine/commit/02e4b7b90ccb740aab28994c1d416f43cd55f281. Need to re-enable by applying [these patches](https://github.com/swift-kim/engine/commits/reenable-vulkan) if you're going to work on it.

I couldn't find a way to override `vulkan_use_x11` without modification to the buildroot. (I tried declaring `vulkan_use_x11` using  `declare_args` and passing as a GN argument but it didn't have any effect.)

**Comment by swift-kim** [comment]
Impeller build now requires glibc 2.30 (Tizen 6.0). glibc 2.24 (Tizen 5.5) is not compatible:

```cpp
In file included from ../../flutter/impeller/core/shader_types.cc:5:
In file included from ../../flutter/impeller/core/shader_types.h:15:
../../flutter/impeller/geometry/half.h:19:22: error: _Float16 is not supported on this target
using InternalHalf = _Float16;
                     ^
1 error generated.
```

I'll add a temporary workaround to bypass the error.

**Comment by swift-kim** [comment]
The Impeller support for desktop platforms has landed to the embedder API:

- Windows (OpenGL): https://github.com/flutter/engine/commit/e478f1be28dc12e123f86adcfc92a5be23dc185b
- macOS (Metal): https://github.com/flutter/engine/commit/052e22661754d278b33a55deec9c26b0a5d402c1

I think we can now start evaluating Impeller on Tizen using the OpenGL backend. cc @haesik

**Comment by jonahwilliams** [comment]
We don't currently recommend shipping production applications with the OpenGL backend.

**Comment by xuelian-bai** [comment]
It's possible to enable vulkan backend on Tizen, we need time to investigate about impeller

**Comment by JSUYA** [comment]
These patches are for running the impeller that @xiaowei-guan worked on in the 3.21 candidate branch.
engine : https://github.com/xiaowei-guan/engine/commits/flutter-3.21-candidate.10/
embedder : https://github.com/xiaowei-guan/embedder/commits/flutter-3.21-candidate.10/
+) https://github.com/JSUYA/embedder/commit/f5936942e3aef58c4fad3379975cf2854475d0aa
flutter-tizen : https://github.com/xiaowei-guan/flutter-tizen/commits/3.21-candidate.10/

We can discuss these patches once 3.22 migration is completed.
If there is anything we would like to discuss before a PR for the above patch is created, we can do so on this page.

**Comment by JSUYA** [comment]
@xiaowei-guan 
When i tested impeller, there was no problem with video_player running even without using `ExternalTextureWithType`.
Are there any cases where ExternalTextureWithType must be used?

If you really need `ExternalTextureWithType` ...
I am concerned about putting platform specific code in embedder.h because it will affect future migration.
Can you separate the EmbedderExternalTextureGLImpellerSurface(/PixelBuffer) in  and embedder_external_texture_gl.h. and differentiate them at the gn level? How about adding embedder_tizen.h?

**Comment by xiaowei-guan** [comment]
> @xiaowei-guan When i tested impeller, there was no problem with video_player running even without using `ExternalTextureWithType`. Are there any cases where ExternalTextureWithType must be used?
> 
> If you really need `ExternalTextureWithType` ... I am concerned about putting platform specific code in embedder.h because it will affect future migration. Can you separate the EmbedderExternalTextureGLImpellerSurface(/PixelBuffer) in and embedder_external_texture_gl.h. and differentiate them at the gn level? How about adding embedder_tizen.h?

Hello, @JSUYA 
> When i tested impeller, there was no problem with video_player running even without using ExternalTextureWithType.
Are there any cases where ExternalTextureWithType must be used?

Embedder create different texture based on the `ExternalTextureWithType` for impeller, we can refer to this 
https://github.com/xiaowei-guan/engine/blob/flutter-3.21-candidate.10/shell/platform/embedder/embedder_external_texture_resolver.cc#L30-L37
because Impeller encapsulates the OpenGL interface in impeller::TextureGLES class, so embedder need call different API 
according to `ExternalTextureWithType` .

>If you really need ExternalTextureWithType ...
I am concerned about putting platform specific code in embedder.h because it will affect future migration.

yes, we can move all these code to embedder_tizen.h first.  Later we can redesign the interface to fit Tizen and other platform.

>Can you separate the EmbedderExternalTextureGLImpellerSurface(/PixelBuffer) in and embedder_external_texture_gl.h. and differentiate them at the gn level?

I think we can separate the EmbedderExternalTextureGLImpellerSurface(/PixelBuffer), but can't differentiate them at the gn level.

**Comment by xiaowei-guan** [comment]
https://github.com/flutter/flutter/issues/143809

**Comment by jonahwilliams** [comment]
We don't have either Vulkan or GLES fully wired up in the embedder API (contributions welcome!) but if possible, I would recommend using Vulkan where supported. Almost all of our engineering effort is going into Metal and Vulkan support, whereas GLES is intended to be the broadly supported compatibility backend that isn't necessarily the most performant.

**Comment by xiaowei-guan** [comment]
https://github.com/flutter/engine/pull/55490

**Comment by xiaowei-guan** [comment]
[[Impeller] implement external texture gl for embedder.](https://github.com/flutter/engine/pull/56277)

**Comment by xiaowei-guan** [comment]
Support render texture for vulkan + impeller
https://github.com/flutter-tizen/flutter/pull/17
